# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install ripgrep
RUN apk add --no-cache ripgrep

# Create app directory
WORKDIR /app

# Install dependencies and build
COPY package.json tsconfig.json .
COPY src ./src

RUN npm install --ignore-scripts && npm run build

# Expose nothing (stdio)

# Run the MCP server
CMD ["node", "dist/index.js"]
